### ISSUE TITLE
Support "by @user" via code snippet like 

### ISSUE THREAD

**Issue by andpiazza** [Benunc/better-click-to-tweet#31]
A suggestion for improvement
### Idea
When tweeting a quote, it is very relevant to distinguish the author of the quote (by @ user) and the content creator (via @ author).
Via is already supported in such an elegant way... here's the opportunity to tackle "by @ user " using a parameter on the code snippet.

### Why Today's Implementation doesn't work
If we simply add the "by @ user" to the snippet like this:
`[bctt tweet="This is NOT a good way to implement it! by @ user"]`
here are the issues we face:
1. no clear distinction between the quote and the "by @ user" (similar to "via")
1. appears on the box rendered on the screen - extra words
1. each quote (or post, or page) might have one (or multiple) "by @ user" to reference, so we could handle it by the code snippet

### Suggestion
Here's a simple implementation, adding the existing parameter for simmetry:
`[bctt tweet="This is a GREAT way to implement it!" by="byuser" via="viauser"]`

### References
[Just like "url", "via" and "prompt" parameter ](https://www.betterclicktotweet.com/better-click-to-tweet-power-user-guide/#customdesign)

**Comment by Benunc** [comment]
So it appears that I should check my messages from GitHub more regularly... :-) 

I really like this feature request, and will spend some time looking into this. Thanks!

**Comment by Benunc** [comment]
After reviewing this, I am going to close it for the following reasons:

1. The `via` attribute of the shortcode/block in WordPress corresponds with the "via" component on the actual API from twitter (see their docs here: https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview ) which is handy because it's internationalized/translatable, and something that is handled on Twitter's end.

2. There is a filter on the shortcode attributes for adding additional attributes programmatically, which would facitilate a custom plugin to be able to add the functionality you need in. The filter you are looking for is `bctt_atts` which filters all the attributes. If you targeted that filter with a callback function that adds an additional attribute, and then some logic to create that `by` attribute, it would definitely be useful!

Thanks!
